"""自定义角色的 Cerbos 策略生成 — 命名空间归属 + 可回滚写入。

设计依据：docs/manage_role_design.md §4.1 角色定义 vs Cerbos 策略。

修复三项问题：
1. 写入路径落在策略根目录下（{root}/derived_roles/），项目级角色无命名空间归属；
   现按 role_definitions.project_id 写入对应项目目录，平台级角色仍写根目录。
2. 资源策略文件名按 kb / doc 前缀硬编码，只能表达 RAG 的两种资源；
   现按策略索引把 action 反查到资源类型，支持任意项目自定义类型。
3. 写入与数据库提交无法互相回滚；本模块保留被改写文件的原始内容，
   调用方在数据库操作失败时可调用 restore() 还原文件系统。
"""

from __future__ import annotations

from dataclasses import dataclass, field
from pathlib import Path

_DERIVED_ROLES_FILE = "custom_roles.yaml"
_GENERATED_HEADER = (
    "# Auto-generated by Permission Service role management API. Do not edit manually.\n"
)


class PolicyWriteError(Exception):
    """策略生成失败，调用方应拒绝该请求。"""


@dataclass
class PolicyTransaction:
    """记录本次写入触及的文件及其原始内容，用于失败回滚。

    original 中值为 None 表示该文件在写入前不存在，回滚时应删除。
    """

    original: dict[Path, str | None] = field(default_factory=dict)

    def capture(self, path: Path) -> None:
        if path in self.original:
            return
        self.original[path] = path.read_text() if path.exists() else None

    def restore(self) -> None:
        """还原全部被触及的文件。回滚过程本身不抛异常。"""
        for path, content in self.original.items():
            try:
                if content is None:
                    if path.exists():
                        path.unlink()
                else:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content)
            except OSError:
                continue


def _namespace_dir(project_id: str | None) -> Path:
    """角色所属的策略命名空间目录。

    项目级角色写入 {root}/{project_id}/，平台级角色（project_id 为空）写入 {root}/。
    两种布局都能被 cerbos_policy_parser 索引到。
    """
    from app.config import get_cerbos_policies_dir

    root = get_cerbos_policies_dir()
    return root / project_id if project_id else root


def resolve_resource_types(
    permissions: list[str], project_id: str | None,
) -> dict[str, list[str]]:
    """把动作列表反查为 {资源类型: [动作]}。

    动作到资源类型的对应关系取自策略索引：某动作出现在哪些资源策略的 rules 中，
    就属于哪些资源类型。一个动作可能属于多个资源类型，此时每个类型都会生成规则。

    Raises:
        PolicyWriteError: 存在无法归属到任何已知资源类型的动作。此时拒绝写入，
            否则会生成引用未定义资源的规则。
    """
    from services.cerbos_policy_parser import get_policy_index

    index = get_policy_index()
    visible = index.visible_resources(project_id)

    grouped: dict[str, list[str]] = {}
    unmapped: list[str] = []

    for action in permissions:
        owners = [
            resource_type
            for resource_type in visible
            if action in index.actions_for_resource(resource_type, project_id)
        ]
        if not owners:
            unmapped.append(action)
            continue
        for resource_type in owners:
            grouped.setdefault(resource_type, []).append(action)

    if unmapped:
        scope = f"项目 '{project_id}'" if project_id else "平台级策略"
        raise PolicyWriteError(
            f"以下动作在{scope}的资源策略中未定义，无法生成角色规则: "
            f"{', '.join(sorted(unmapped))}。请先在资源策略中声明这些动作。"
        )

    return {rt: sorted(set(actions)) for rt, actions in grouped.items()}


def _derived_roles_document(entries: dict[str, list[str]]) -> str:
    """生成 derived_roles 文件内容。

    entries: {角色名: 父角色列表}
    条件恒为真，实际准入由资源策略的 rules 决定。
    """
    import yaml as _yaml

    definitions = [
        {
            "name": name,
            "parentRoles": parents or ["user"],
            "condition": {"match": {"expr": "true"}},
        }
        for name, parents in sorted(entries.items())
    ]
    body = _yaml.safe_dump(
        {
            "apiVersion": "api.cerbos.dev/v1",
            "derivedRoles": {"name": "custom_roles", "definitions": definitions},
        },
        sort_keys=False,
        allow_unicode=True,
    )
    return _GENERATED_HEADER + body


def _read_derived_entries(path: Path) -> dict[str, list[str]]:
    """读取现有 derived_roles 文件中的角色定义。

    解析失败时返回空字典，由调用方以新内容整体覆盖。
    """
    import yaml as _yaml

    if not path.exists():
        return {}
    try:
        doc = _yaml.safe_load(path.read_text()) or {}
    except Exception:
        return {}
    definitions = (doc.get("derivedRoles") or {}).get("definitions") or []
    return {
        d["name"]: d.get("parentRoles") or []
        for d in definitions
        if isinstance(d, dict) and d.get("name")
    }


def _resource_policy_document(
    resource_type: str, role: str, actions: list[str],
) -> str:
    """生成单个资源策略文件内容。"""
    import yaml as _yaml

    body = _yaml.safe_dump(
        {
            "apiVersion": "api.cerbos.dev/v1",
            "resourcePolicy": {
                "version": "default",
                "resource": resource_type,
                "importDerivedRoles": ["custom_roles"],
                "rules": [
                    {
                        "actions": actions,
                        "effect": "EFFECT_ALLOW",
                        "derivedRoles": [role],
                    }
                ],
            },
        },
        sort_keys=False,
        allow_unicode=True,
    )
    return _GENERATED_HEADER + body


def _resource_policy_path(ns: Path, resource_type: str, role: str) -> Path:
    return ns / "resource_policies" / f"custom_{resource_type}_{role}.yaml"


def write_role_policies(
    name: str,
    parent_roles: list[str],
    permissions: list[str],
    project_id: str | None,
) -> PolicyTransaction:
    """为自定义角色生成派生角色定义与资源规则。

    写入前先校验动作可归属，再逐文件写入并记录原始内容。
    任一步失败自动还原已写入的文件后抛出。

    Returns:
        PolicyTransaction，调用方在后续数据库操作失败时调用 restore()。
    """
    grouped = resolve_resource_types(permissions, project_id)
    ns = _namespace_dir(project_id)
    tx = PolicyTransaction()

    try:
        # ── 派生角色：与同命名空间下已有条目合并 ──
        dr_path = ns / "derived_roles" / _DERIVED_ROLES_FILE
        tx.capture(dr_path)
        entries = _read_derived_entries(dr_path)
        entries[name] = parent_roles or ["user"]
        dr_path.parent.mkdir(parents=True, exist_ok=True)
        dr_path.write_text(_derived_roles_document(entries))

        # ── 资源规则：每个资源类型一个文件 ──
        # 先清掉该角色可能残留的旧资源文件，避免改权限后旧规则继续生效
        for stale in _existing_resource_policy_paths(ns, name):
            if stale not in {
                _resource_policy_path(ns, rt, name) for rt in grouped
            }:
                tx.capture(stale)
                stale.unlink()

        for resource_type, actions in grouped.items():
            rp_path = _resource_policy_path(ns, resource_type, name)
            tx.capture(rp_path)
            rp_path.parent.mkdir(parents=True, exist_ok=True)
            rp_path.write_text(
                _resource_policy_document(resource_type, name, actions)
            )
    except PolicyWriteError:
        tx.restore()
        raise
    except OSError as exc:
        tx.restore()
        raise PolicyWriteError(f"策略文件写入失败: {exc}") from exc

    return tx


def _existing_resource_policy_paths(ns: Path, role: str) -> list[Path]:
    """列出该角色在命名空间下已生成的资源策略文件。"""
    rp_dir = ns / "resource_policies"
    if not rp_dir.is_dir():
        return []
    return sorted(rp_dir.glob(f"custom_*_{role}.yaml"))


def remove_role_policies(name: str, project_id: str | None) -> PolicyTransaction:
    """删除自定义角色对应的策略文件。

    同时清理平台级与项目级两处，覆盖历史上写入根目录的遗留文件。

    Returns:
        PolicyTransaction，调用方在后续数据库操作失败时调用 restore()。
    """
    from app.config import get_cerbos_policies_dir

    namespaces = [_namespace_dir(project_id)]
    root = get_cerbos_policies_dir()
    if root not in namespaces:
        # 兼容早期版本：无论角色是否属于项目，都清理根目录下的遗留条目
        namespaces.append(root)

    tx = PolicyTransaction()
    try:
        for ns in namespaces:
            dr_path = ns / "derived_roles" / _DERIVED_ROLES_FILE
            if dr_path.exists():
                entries = _read_derived_entries(dr_path)
                if name in entries:
                    tx.capture(dr_path)
                    del entries[name]
                    if entries:
                        dr_path.write_text(_derived_roles_document(entries))
                    else:
                        dr_path.unlink()

            for rp_path in _existing_resource_policy_paths(ns, name):
                tx.capture(rp_path)
                rp_path.unlink()
    except OSError as exc:
        tx.restore()
        raise PolicyWriteError(f"策略文件清理失败: {exc}") from exc

    return tx
