"""自定义角色的 Cerbos 策略生成 — 命名空间归属 + 可回滚写入。

设计依据：docs/permission_model_v2.md §1 目录布局 + §7 明令禁止。

Cerbos 的模块 ID 是全局的：资源策略按 (resource, version) 唯一，派生角色集合按
name 唯一，**目录层级不构成命名空间**。因此生成策略时必须自己保证不撞车：

1. 派生角色集合名按项目取（custom_roles_{project}）。
   此前全项目共用 "custom_roles" 这一个名字，两个项目各有一个自定义角色就产生
   两个同名集合，而各自生成的资源策略都写 importDerivedRoles: [custom_roles]，
   解析到哪一份不确定。
2. 只允许生成**归属于本项目**的资源类型的策略。
   platform / project_permission 对每个项目都可见，但它们是平台层资源；
   若允许项目级角色对它们生成规则，会与 platform/ 下的策略构成同一个模块 ID，
   且生成的派生角色条件恒为真、父角色为 user —— 等于把平台权限发给所有登录用户。
3. 自定义角色必须归属某个项目。
   平台层按设计只有两个文件、不随项目增减（§1），没有"平台级自定义派生角色"
   这一形态；无项目归属的角色也无处可写（写到策略根目录同样会撞项目的模块 ID）。

写入与数据库提交可互相回滚：本模块保留被改写文件的原始内容，
调用方在数据库操作失败时调用 restore() 还原文件系统。
"""

from __future__ import annotations

import re
from dataclasses import dataclass, field
from pathlib import Path

_DERIVED_ROLES_FILE = "custom_roles.yaml"
_GENERATED_HEADER = (
    "# Auto-generated by Permission Service role management API. Do not edit manually.\n"
)

# 早期版本全项目共用的派生角色集合名，迁移时用于识别遗留文件
_LEGACY_DERIVED_SET = "custom_roles"


class PolicyWriteError(Exception):
    """策略生成失败，调用方应拒绝该请求。"""


@dataclass
class PolicyTransaction:
    """记录本次写入触及的文件及其原始内容，用于失败回滚。

    original 中值为 None 表示该文件在写入前不存在，回滚时应删除。
    """

    original: dict[Path, str | None] = field(default_factory=dict)

    def capture(self, path: Path) -> None:
        if path in self.original:
            return
        self.original[path] = path.read_text() if path.exists() else None

    def restore(self) -> None:
        """还原全部被触及的文件。回滚过程本身不抛异常。"""
        for path, content in self.original.items():
            try:
                if content is None:
                    if path.exists():
                        path.unlink()
                else:
                    path.parent.mkdir(parents=True, exist_ok=True)
                    path.write_text(content)
            except OSError:
                continue


def require_project_scope(project_id: str | None) -> str:
    """自定义角色必须归属某个项目。

    Raises:
        PolicyWriteError: project_id 为空。
    """
    if not project_id:
        raise PolicyWriteError(
            "自定义角色必须归属一个项目。平台层策略按设计只有 platform.yaml 与 "
            "project_permission.yaml 两个文件、不随项目增减，没有平台级自定义派生"
            "角色这一形态；平台权限通过平台角色绑定或按功能的授权记录下发。"
        )
    return project_id


def _namespace_dir(project_id: str) -> Path:
    """角色所属的策略命名空间目录 {root}/{project_id}/。"""
    from app.config import get_cerbos_policies_dir

    return get_cerbos_policies_dir() / project_id


def derived_set_name(project_id: str) -> str:
    """该项目自定义派生角色集合的名字。

    Cerbos 的派生角色集合名全局唯一，必须带项目前缀。项目 ID 的取值域是
    ^[a-z][a-z0-9-]+$（见 api/project_routes.py），把 '-' 归一为 '_' 不会与
    另一个项目 ID 撞名，因为 '_' 本身不在取值域内。
    """
    return f"{_LEGACY_DERIVED_SET}_{re.sub(r'[^a-z0-9]', '_', project_id)}"


def resolve_resource_types(
    permissions: list[str], project_id: str,
) -> dict[str, list[str]]:
    """把动作列表反查为 {资源类型: [动作]}。

    动作到资源类型的对应关系取自策略索引：某动作出现在该项目**自有**资源策略的
    rules 中，就属于该资源类型。一个动作可能属于多个自有资源类型，
    此时每个类型都会生成规则。

    只认本项目命名空间的资源（resources_owned_by），不认全局可见的平台层资源：
    平台层的准入不经过自定义派生角色，且在项目目录里生成 platform 资源策略会与
    platform/ 下的文件构成同一个 Cerbos 模块 ID。

    Raises:
        PolicyWriteError: 存在无法归属到本项目任何资源类型的动作。
    """
    from services.cerbos_policy_parser import get_policy_index

    index = get_policy_index()
    owned = index.resources_owned_by(project_id)

    grouped: dict[str, list[str]] = {}
    unmapped: list[str] = []

    for action in permissions:
        owners = [
            resource_type
            for resource_type in owned
            if action in index.actions_for_resource(resource_type, project_id)
        ]
        if not owners:
            unmapped.append(action)
            continue
        for resource_type in owners:
            grouped.setdefault(resource_type, []).append(action)

    if unmapped:
        platform_only = sorted(
            a
            for a in unmapped
            if any(
                a in index.actions_for_resource(rt, project_id)
                for rt in index.visible_resources(project_id) - owned
            )
        )
        detail = (
            f"以下动作在项目 '{project_id}' 的资源策略中未定义，无法生成角色规则: "
            f"{', '.join(sorted(unmapped))}。请先在该项目的资源策略中声明这些动作。"
        )
        if platform_only:
            detail += (
                f" 其中 {', '.join(platform_only)} 属于平台层资源，"
                "不能通过项目自定义角色授予 —— 平台权限请用平台角色绑定或"
                "按功能的平台授权记录下发。"
            )
        raise PolicyWriteError(detail)

    return {rt: sorted(set(actions)) for rt, actions in grouped.items()}


def _derived_roles_document(entries: dict[str, list[str]], set_name: str) -> str:
    """生成 derived_roles 文件内容。

    entries: {角色名: 激活角色列表}
    条件恒为真，实际准入由资源策略的 rules 决定。
    """
    import yaml as _yaml

    definitions = [
        {
            "name": name,
            "parentRoles": parents or ["user"],
            "condition": {"match": {"expr": "true"}},
        }
        for name, parents in sorted(entries.items())
    ]
    body = _yaml.safe_dump(
        {
            "apiVersion": "api.cerbos.dev/v1",
            "derivedRoles": {"name": set_name, "definitions": definitions},
        },
        sort_keys=False,
        allow_unicode=True,
    )
    return _GENERATED_HEADER + body


def _read_derived_entries(path: Path) -> dict[str, list[str]]:
    """读取现有 derived_roles 文件中的角色定义。

    解析失败时返回空字典，由调用方以新内容整体覆盖。
    """
    import yaml as _yaml

    if not path.exists():
        return {}
    try:
        doc = _yaml.safe_load(path.read_text()) or {}
    except Exception:
        return {}
    definitions = (doc.get("derivedRoles") or {}).get("definitions") or []
    return {
        d["name"]: d.get("parentRoles") or []
        for d in definitions
        if isinstance(d, dict) and d.get("name")
    }


def _resource_policy_document(
    resource_type: str, role: str, actions: list[str], set_name: str,
) -> str:
    """生成单个资源策略文件内容。

    注意 resource + version 构成 Cerbos 全局模块 ID：调用方必须已确认
    resource_type 归属本项目（见 resolve_resource_types）。
    """
    import yaml as _yaml

    body = _yaml.safe_dump(
        {
            "apiVersion": "api.cerbos.dev/v1",
            "resourcePolicy": {
                "version": "default",
                "resource": resource_type,
                "importDerivedRoles": [set_name],
                "rules": [
                    {
                        "actions": actions,
                        "effect": "EFFECT_ALLOW",
                        "derivedRoles": [role],
                    }
                ],
            },
        },
        sort_keys=False,
        allow_unicode=True,
    )
    return _GENERATED_HEADER + body


def _resource_policy_path(ns: Path, resource_type: str, role: str) -> Path:
    return ns / "resource_policies" / f"custom_{resource_type}_{role}.yaml"


def _retarget_legacy_imports(
    ns: Path, set_name: str, tx: PolicyTransaction, skip: set[Path],
) -> None:
    """把本命名空间下仍引用旧全局集合名的自定义资源策略改指向新集合名。

    早期版本所有项目共用 "custom_roles"。改名后，同项目里**其他**自定义角色的
    资源策略仍写着旧名字，会引用到一个已不存在（或属于别的项目）的集合。
    这里在写入时顺带把它们改过来，避免留下悬空引用。
    """
    import yaml as _yaml

    rp_dir = ns / "resource_policies"
    if not rp_dir.is_dir():
        return

    for path in sorted(rp_dir.glob("custom_*.yaml")):
        if path in skip:
            continue
        try:
            doc = _yaml.safe_load(path.read_text()) or {}
        except Exception:
            continue
        policy = doc.get("resourcePolicy")
        if not isinstance(policy, dict):
            continue
        imports = policy.get("importDerivedRoles") or []
        if _LEGACY_DERIVED_SET not in imports:
            continue
        policy["importDerivedRoles"] = [
            set_name if i == _LEGACY_DERIVED_SET else i for i in imports
        ]
        tx.capture(path)
        path.write_text(
            _GENERATED_HEADER
            + _yaml.safe_dump(doc, sort_keys=False, allow_unicode=True)
        )


def write_role_policies(
    name: str,
    parent_roles: list[str],
    permissions: list[str],
    project_id: str | None,
) -> PolicyTransaction:
    """为自定义角色生成派生角色定义与资源规则。

    写入前先校验项目归属与动作归属，再逐文件写入并记录原始内容。
    任一步失败自动还原已写入的文件后抛出。

    Returns:
        PolicyTransaction，调用方在后续数据库操作失败时调用 restore()。
    """
    project = require_project_scope(project_id)
    grouped = resolve_resource_types(permissions, project)
    ns = _namespace_dir(project)
    set_name = derived_set_name(project)
    tx = PolicyTransaction()

    try:
        # ── 派生角色：与同项目下已有条目合并 ──
        dr_path = ns / "derived_roles" / _DERIVED_ROLES_FILE
        tx.capture(dr_path)
        entries = _read_derived_entries(dr_path)
        entries[name] = parent_roles or ["user"]
        dr_path.parent.mkdir(parents=True, exist_ok=True)
        dr_path.write_text(_derived_roles_document(entries, set_name))

        # ── 资源规则：每个资源类型一个文件 ──
        # 先清掉该角色可能残留的旧资源文件，避免改权限后旧规则继续生效
        written = {_resource_policy_path(ns, rt, name) for rt in grouped}
        for stale in _existing_resource_policy_paths(ns, name):
            if stale not in written:
                tx.capture(stale)
                stale.unlink()

        for resource_type, actions in grouped.items():
            rp_path = _resource_policy_path(ns, resource_type, name)
            tx.capture(rp_path)
            rp_path.parent.mkdir(parents=True, exist_ok=True)
            rp_path.write_text(
                _resource_policy_document(resource_type, name, actions, set_name)
            )

        # ── 同项目内其他自定义角色的遗留引用一并改名 ──
        _retarget_legacy_imports(ns, set_name, tx, skip=written)
    except PolicyWriteError:
        tx.restore()
        raise
    except OSError as exc:
        tx.restore()
        raise PolicyWriteError(f"策略文件写入失败: {exc}") from exc

    return tx


def _existing_resource_policy_paths(ns: Path, role: str) -> list[Path]:
    """列出该角色在命名空间下已生成的资源策略文件。"""
    rp_dir = ns / "resource_policies"
    if not rp_dir.is_dir():
        return []
    return sorted(rp_dir.glob(f"custom_*_{role}.yaml"))


def remove_role_policies(name: str, project_id: str | None) -> PolicyTransaction:
    """删除自定义角色对应的策略文件。

    同时清理策略根目录下的遗留条目：早期版本把无项目归属的角色写在那里，
    现在该形态已不允许，但存量文件仍需能被删掉。

    Returns:
        PolicyTransaction，调用方在后续数据库操作失败时调用 restore()。
    """
    from app.config import get_cerbos_policies_dir

    root = get_cerbos_policies_dir()
    namespaces: list[tuple[Path, str]] = []
    if project_id:
        namespaces.append((_namespace_dir(project_id), derived_set_name(project_id)))
    namespaces.append((root, _LEGACY_DERIVED_SET))

    tx = PolicyTransaction()
    try:
        for ns, set_name in namespaces:
            dr_path = ns / "derived_roles" / _DERIVED_ROLES_FILE
            if dr_path.exists():
                entries = _read_derived_entries(dr_path)
                if name in entries:
                    tx.capture(dr_path)
                    del entries[name]
                    if entries:
                        dr_path.write_text(
                            _derived_roles_document(entries, set_name)
                        )
                    else:
                        dr_path.unlink()

            for rp_path in _existing_resource_policy_paths(ns, name):
                tx.capture(rp_path)
                rp_path.unlink()
    except OSError as exc:
        tx.restore()
        raise PolicyWriteError(f"策略文件清理失败: {exc}") from exc

    return tx
