"""init_all_tables

Revision ID: 2355d6c9498d
Revises: 
Create Date: 2026-07-30 13:57:10.909267

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '2355d6c9498d'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('acl_entries',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False, comment='user:alice | group:eng | role:viewer'),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='kb | document'),
    sa.Column('resource_id', sa.String(length=255), nullable=False, comment='资源 ID'),
    sa.Column('action', sa.String(length=64), nullable=False, comment='kb:read | doc:view | doc:download | ...'),
    sa.Column('granted_by', sa.String(length=255), nullable=False, comment='授予者'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('expires_at', sa.DateTime(timezone=True), nullable=True, comment='可选的过期时间'),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal', 'resource_type', 'resource_id', 'action', name='uq_acl_principal_resource_action')
    )
    op.create_index('idx_acl_principal', 'acl_entries', ['principal'], unique=False, postgresql_where='NOT revoked')
    op.create_index('idx_acl_resource', 'acl_entries', ['resource_type', 'resource_id'], unique=False, postgresql_where='NOT revoked')
    op.create_index('idx_acl_tenant', 'acl_entries', ['tenant_id'], unique=False)
    op.create_table('mount_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('doc_id', sa.String(length=255), nullable=False),
    sa.Column('kb_id', sa.String(length=255), nullable=False),
    sa.Column('unlinked', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('doc_id', 'kb_id', name='uq_doc_kb')
    )
    op.create_table('permission_changes',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('event_type', sa.String(length=128), nullable=False, comment='ACL_GRANTED | ACL_REVOKED | ROLE_BOUND | RESTRICTION_ADDED | ...'),
    sa.Column('resource_type', sa.String(length=64), nullable=True),
    sa.Column('resource_id', sa.String(length=255), nullable=True),
    sa.Column('kb_id', sa.String(length=255), nullable=True, comment='用于 KB 粒度事件展开'),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('change_detail', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='变更详情'),
    sa.Column('version', sa.BigInteger(), nullable=False, comment='全局单调递增版本号'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_pc_kb', 'permission_changes', ['kb_id'], unique=False)
    op.create_index('idx_pc_resource', 'permission_changes', ['resource_type', 'resource_id'], unique=False)
    op.create_index('idx_pc_version', 'permission_changes', ['version'], unique=False)
    op.create_table('resource_registry',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('resource_type', sa.String(length=64), nullable=False, comment='kb|document|directory'),
    sa.Column('resource_id', sa.String(length=255), nullable=False, comment='RAG 系统中的资源 ID'),
    sa.Column('tenant_id', sa.String(length=255), nullable=False, comment='所属租户'),
    sa.Column('owner', sa.String(length=255), nullable=False, comment='user:xxx 格式'),
    sa.Column('retired', sa.Boolean(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('resource_type', 'resource_id', name='uq_resource_type_id')
    )
    op.create_table('restrictions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('restriction_type', sa.String(length=64), nullable=False, comment='subject_ban (型一) | resource_restriction (型二)'),
    sa.Column('principal', sa.String(length=255), nullable=True, comment='型一：被封禁的主体'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='型二：受限的资源类型'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='型二：受限的资源 ID'),
    sa.Column('reason', sa.Text(), nullable=True),
    sa.Column('created_by', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('removed', sa.Boolean(), nullable=False),
    sa.Column('removed_at', sa.DateTime(timezone=True), nullable=True),
    sa.CheckConstraint("(restriction_type = 'subject_ban' AND principal IS NOT NULL) OR (restriction_type = 'resource_restriction' AND resource_type IS NOT NULL)", name='ck_restriction_type'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('role_bindings',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=255), nullable=False),
    sa.Column('principal', sa.String(length=255), nullable=False, comment='user:alice | group:eng'),
    sa.Column('role', sa.String(length=64), nullable=False, comment='kb_reader | kb_writer | kb_admin | admin'),
    sa.Column('resource_type', sa.String(length=64), nullable=True, comment='可选：限定到特定资源类型的 KB'),
    sa.Column('resource_id', sa.String(length=255), nullable=True, comment='可选：限定到特定 KB'),
    sa.Column('granted_by', sa.String(length=255), nullable=False),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('principal', 'role', 'resource_type', 'resource_id', name='uq_role_binding')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('role_bindings')
    op.drop_table('restrictions')
    op.drop_table('resource_registry')
    op.drop_index('idx_pc_version', table_name='permission_changes')
    op.drop_index('idx_pc_resource', table_name='permission_changes')
    op.drop_index('idx_pc_kb', table_name='permission_changes')
    op.drop_table('permission_changes')
    op.drop_table('mount_registry')
    op.drop_index('idx_acl_tenant', table_name='acl_entries')
    op.drop_index('idx_acl_resource', table_name='acl_entries', postgresql_where='NOT revoked')
    op.drop_index('idx_acl_principal', table_name='acl_entries', postgresql_where='NOT revoked')
    op.drop_table('acl_entries')
    # ### end Alembic commands ###
