"""add_is_enabled_allow_download_to_resource_registry

Revision ID: 36b35f67fea5
Revises: 8c8a369d3fea
Create Date: 2026-07-30 20:58:12.318778

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '36b35f67fea5'
down_revision: Union[str, Sequence[str], None] = '8c8a369d3fea'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # 使用 server_default 填充现有行的默认值，避免 NOT NULL 冲突
    op.add_column('resource_registry', sa.Column(
        'is_enabled', sa.Boolean(), nullable=False, server_default=sa.text('true'),
        comment='文档是否启用（运营停用=不可检索）。由 B-DOC MountEnabledChanged 事件同步维护。'
    ))
    op.add_column('resource_registry', sa.Column(
        'allow_download', sa.Boolean(), nullable=False, server_default=sa.text('true'),
        comment='是否允许下载。仅对 document 类型生效，Cerbos doc:download 规则使用。'
    ))


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('resource_registry', 'allow_download')
    op.drop_column('resource_registry', 'is_enabled')
    # ### end Alembic commands ###
