"""add_tenants_and_tenant_memberships

Revision ID: bcd2c67782dc
Revises: 9b1c5e7d3f2a
Create Date: 2026-08-01 09:07:22.400270

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bcd2c67782dc'
down_revision: Union[str, Sequence[str], None] = '9b1c5e7d3f2a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('tenants',
    sa.Column('id', sa.String(length=64), nullable=False, comment='租户唯一标识（如 tenant-dev, acme-corp）'),
    sa.Column('name', sa.String(length=255), nullable=False, comment='显示名称（如 开发测试租户）'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='租户描述'),
    sa.Column('status', sa.String(length=16), nullable=False, comment='active | suspended | deleted'),
    sa.Column('created_by', sa.String(length=255), nullable=False, comment='创建者 (user:xxx)'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_tenants_status', 'tenants', ['status'], unique=False)
    op.create_table('tenant_memberships',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('tenant_id', sa.String(length=64), nullable=False, comment='所属租户'),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='用户标识 (user:xxx 格式，来自 IdP)'),
    sa.Column('role', sa.String(length=64), nullable=False, comment='tenant_admin | member'),
    sa.Column('granted_by', sa.String(length=255), nullable=False, comment='授予者'),
    sa.Column('granted_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('revoked', sa.Boolean(), nullable=False),
    sa.Column('revoked_at', sa.DateTime(timezone=True), nullable=True),
    sa.ForeignKeyConstraint(['tenant_id'], ['tenants.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('tenant_id', 'user_id', name='uq_tm_tenant_user')
    )
    op.create_index('idx_tm_tenant', 'tenant_memberships', ['tenant_id'], unique=False, postgresql_where='NOT revoked')
    op.create_index('idx_tm_user', 'tenant_memberships', ['user_id'], unique=False, postgresql_where='NOT revoked')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_tm_user', table_name='tenant_memberships', postgresql_where='NOT revoked')
    op.drop_index('idx_tm_tenant', table_name='tenant_memberships', postgresql_where='NOT revoked')
    op.drop_table('tenant_memberships')
    op.drop_index('idx_tenants_status', table_name='tenants')
    op.drop_table('tenants')
    # ### end Alembic commands ###
