"""add_role_definitions

Revision ID: dddcf4c5164c
Revises: bcd2c67782dc
Create Date: 2026-08-01 12:16:04.500641

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'dddcf4c5164c'
down_revision: Union[str, Sequence[str], None] = 'bcd2c67782dc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('role_definitions',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('name', sa.String(length=64), nullable=False, comment='角色名: kb_reader, kb_writer, kb_admin, admin 等'),
    sa.Column('description', sa.String(length=512), nullable=False, comment='角色描述'),
    sa.Column('parent_keycloak_roles', postgresql.JSONB(astext_type=sa.Text()), nullable=False, comment='父级 Keycloak 角色: ["user"] 或 ["system_admin"]'),
    sa.Column('is_system', sa.Boolean(), nullable=False, comment='系统内置角色（不可删除）'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    op.drop_table('role_definitions')
    # ### end Alembic commands ###
