"""add_user_cache_table

Revision ID: ff26c6d76167
Revises: 2355d6c9498d
Create Date: 2026-07-30 16:42:52.989987

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ff26c6d76167'
down_revision: Union[str, Sequence[str], None] = '2355d6c9498d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_cache',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.String(length=255), nullable=False, comment='Keycloak user ID (sub)'),
    sa.Column('username', sa.String(length=255), nullable=False, comment='preferred_username'),
    sa.Column('email', sa.String(length=255), nullable=True, comment='用户邮箱'),
    sa.Column('first_name', sa.String(length=255), nullable=True),
    sa.Column('last_name', sa.String(length=255), nullable=True),
    sa.Column('tenant_id', sa.String(length=255), nullable=True, comment='租户 ID（从用户属性映射）'),
    sa.Column('roles', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='Realm roles 列表'),
    sa.Column('groups', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='所属组列表'),
    sa.Column('attributes', postgresql.JSONB(astext_type=sa.Text()), nullable=True, comment='用户属性原始 JSON'),
    sa.Column('enabled', sa.Boolean(), nullable=False, comment='Keycloak 中是否启用'),
    sa.Column('last_synced_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False, comment='最后同步时间'),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('user_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_cache')
    # ### end Alembic commands ###
